# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Vox Native Transcription.

Build with: pyinstaller vox-native-transcription.spec
Output will be in dist/Vox/

Version is auto-detected from:
1. VERSION file (if exists, e.g., written by CI)
2. Git tag (git describe --tags)
3. Fallback to 0.0.0-dev
"""

import os
import subprocess


def get_version():
    """
    Get version from VERSION file or git tags.
    
    Priority:
    1. VERSION file (written by CI or manual)
    2. Git tag (for local builds)
    3. Fallback to 0.0.0-dev
    """
    # Try VERSION file first (CI writes this)
    if os.path.exists('VERSION'):
        with open('VERSION', 'r') as f:
            version = f.read().strip()
            if version:
                print(f"Version from VERSION file: {version}")
                return version
    
    # Try git describe
    try:
        result = subprocess.run(
            ['git', 'describe', '--tags', '--abbrev=0'],
            capture_output=True,
            text=True,
            check=True
        )
        tag = result.stdout.strip()
        # Strip 'v' prefix if present
        version = tag[1:] if tag.startswith('v') else tag
        print(f"Version from git tag: {version}")
        
        # Write VERSION file for Inno Setup to read
        with open('VERSION', 'w') as f:
            f.write(version)
        
        return version
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    
    # Fallback
    version = '0.0.0-dev'
    print(f"No version found, using fallback: {version}")
    
    # Write VERSION file for Inno Setup to read
    with open('VERSION', 'w') as f:
        f.write(version)
    
    return version


version = get_version()

# Data files to include
datas = [
    ('src/ui/resources/style.qss', 'src/ui/resources'),
]

# Hidden imports that PyInstaller might miss
hiddenimports = [
    # Audio libraries
    'webrtcvad',
    'sounddevice',
    '_sounddevice_data',
    
    # Keyboard/mouse hooks
    'keyboard',
    'pynput',
    'pynput.keyboard',
    'pynput.keyboard._win32',
    'pynput.mouse',
    'pynput.mouse._win32',
    
    # Windows automation
    'uiautomation',
    'comtypes',
    'comtypes.client',
    
    # PySide6 modules
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
    
    # Network
    'websockets',
    'websockets.client',
    
    # OpenAI/ElevenLabs
    'openai',
    'elevenlabs',
    'httpx',
    
    # Standard library modules sometimes missed
    'json',
    'asyncio',
    'threading',
    'queue',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude unnecessary modules to reduce size
        'tkinter',
        'matplotlib',
        'PIL',
        'scipy',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Vox',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # No console window (GUI app)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src/ui/resources/icons/app.ico',  # generated by tools/make_icon.py
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Vox',
)
